version: '3.8'

services:
  #  Service 1: Database (Postgres) 
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=appDB
    ports:
      - "5432:5432"

  # Service 3: Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Service 2: FastAPI App 
  web:
    build: .
    command: uvicorn run:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      # Database (Docker mạng nội bộ → dùng tên service)
      - DATABASE_URL=postgresql://postgres:admin123@db/appDB

      # Redis (QUAN TRỌNG)
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      # Auth
      - SECRET_KEY=chuoi_bi_mat_sieu_kho_doan
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

    depends_on:
      - db
      - redis

volumes:
  postgres_data:
